// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: distributionSystemService.proto

#include "distributionSystemService.pb.h"
#include "distributionSystemService.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace distributionSystemService {

static const char* DistributionSystemService_method_names[] = {
  "/distributionSystemService.DistributionSystemService/Ping",
};

std::unique_ptr< DistributionSystemService::Stub> DistributionSystemService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< DistributionSystemService::Stub> stub(new DistributionSystemService::Stub(channel, options));
  return stub;
}

DistributionSystemService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Ping_(DistributionSystemService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status DistributionSystemService::Stub::Ping(::grpc::ClientContext* context, const ::distributionSystemService::Empty& request, ::distributionSystemService::PingResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::distributionSystemService::Empty, ::distributionSystemService::PingResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Ping_, context, request, response);
}

void DistributionSystemService::Stub::async::Ping(::grpc::ClientContext* context, const ::distributionSystemService::Empty* request, ::distributionSystemService::PingResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::distributionSystemService::Empty, ::distributionSystemService::PingResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Ping_, context, request, response, std::move(f));
}

void DistributionSystemService::Stub::async::Ping(::grpc::ClientContext* context, const ::distributionSystemService::Empty* request, ::distributionSystemService::PingResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Ping_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::distributionSystemService::PingResponse>* DistributionSystemService::Stub::PrepareAsyncPingRaw(::grpc::ClientContext* context, const ::distributionSystemService::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::distributionSystemService::PingResponse, ::distributionSystemService::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Ping_, context, request);
}

::grpc::ClientAsyncResponseReader< ::distributionSystemService::PingResponse>* DistributionSystemService::Stub::AsyncPingRaw(::grpc::ClientContext* context, const ::distributionSystemService::Empty& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncPingRaw(context, request, cq);
  result->StartCall();
  return result;
}

DistributionSystemService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      DistributionSystemService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< DistributionSystemService::Service, ::distributionSystemService::Empty, ::distributionSystemService::PingResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](DistributionSystemService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::distributionSystemService::Empty* req,
             ::distributionSystemService::PingResponse* resp) {
               return service->Ping(ctx, req, resp);
             }, this)));
}

DistributionSystemService::Service::~Service() {
}

::grpc::Status DistributionSystemService::Service::Ping(::grpc::ServerContext* context, const ::distributionSystemService::Empty* request, ::distributionSystemService::PingResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace distributionSystemService

